name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, bcmath, sqlite3
          coverage: none

      - name: Install dependencies with Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy .env example
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Setup SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
